### ISSUE TITLE
Allow plain dates in start/end parameter

### ISSUE THREAD

**Issue by jschaeff** [EIDA/eida-statistics#15]
The query `/query?start=2022-06-01` should be accepted. Currently it gives:

BAD REQUEST: invalid value of parameter 'end'

**Comment by vpet98** [comment]
I made it to accept dates only in format 2022-06 (without day). If it is to accept 2022-06-01 as end date, should it return statistics for the whole month of June or until end of May? It seems kind of ambiguous.
