### ISSUE TITLE
Use a templating system for the documentation

### ISSUE THREAD

**Issue by jschaeff** [EIDA/eida-statistics#17]
In order to insert dynamic content (like the full URL) in the documentation, it would be interesting to use a templating system (jinja2 is a popular option).

The URL prefix can be taken from an environment variable like 

```
EIDASTATS_API_HOST=server.exemple.gr
EIDASTATS_API_PATH=/eidaws/statistics/1
```

**Comment by vpet98** [comment]
Just a minor detail:
The webservice works, but a double slash appears after the API path, like statistics/1**//**dataselect. I can remove the one from the name of the method, but maybe it is better to remove it from the EIDASTATS_API_PATH variable?
