### ISSUE TITLE
Change parameter aggregate_on

### ISSUE THREAD

**Issue by jschaeff** [EIDA/eida-statistics#29]
On /public and /restricted methods, change aggregate_on to:

## level

- one value in datacenter,network,station,location,channel
- if no value is provided, the server responds at EIDA level, all datacenters grouped

## details

Will show the details of the query.
Possible values are:

- month or year
- countries

multiple values are allowed. If month and year are specified, reply 400 and a nice detail.

**Comment by vpet98** [comment]
Maybe having input time parameters in months and specifying year in details isn't the best idea. What should be the result if start=2022-10 & end=2023-02? Two rows, the first one with the last few months of 2022 and the second with the first few months of 2023?

Maybe I should force the user specifying something like start=YYYY-01 and end=YYYY-12 in end whenever they ask for year in detail?

**Comment by jschaeff** [comment]
Good point.
I think we should not change the parametes the user makes in input dynamically. We should always respect what the user asked for. If she wants to sum up 6 month, she would request start=2022-06&details=year

I would say it's up to the user to be careful with their requests.

 The tricky part is to show the user the correct enddate of her result. It could be a key/value in the json respnse ?
Instead of `date="2022-03"` have : `startdate="2022-03-01",enddate="2022-03-31"` ?

@javiquinte any comment ?

**Comment by javiquinte** [comment]
I fully support the idea from @jschaeff . If the user requests to sum up some months and aggregate the result as full years it's his/her responsibility.
I don't understand the last point (The tricky part...). Could you @vpet98 show the output of the example described by @jschaeff ?

**Comment by vpet98** [comment]
Right now, each json of the response contains a month field, like `month="2023-05"` if it refers to a specific month or  `month="*"` if no details on month are requested.

**Comment by jschaeff** [comment]
Keeping the same field name for both details makes sense.

But `month/year` is kind of ugly.

What about `date` simply ?

**Comment by vpet98** [comment]
I think this issue is completed! Let's leave it open for a couple of days in case someone wants to suggest any change.
