### ISSUE TITLE
Group all statistics regarding restricted networks in "Other"

### ISSUE THREAD

**Issue by jschaeff** [EIDA/eida-statistics#31]
When giving statistics to a user that is not authorized to see stats
AND
When there is more than one level in the result
Show all the restricted statistics summed up in an "Other" network item.

If there is only one restricted network in the result, reply 403 unauthorized

**Comment by vpet98** [comment]
Can you explain this a little bit more? Isn't there always only one level, whether this is datacenter, network etc.?

Also, with the current design only one network can be specified at a time. Specifying more than one would cancel the restriction idea. So, in the case of specifying something in the network parameter, this cannot be appplied.

I think this could be applied only in the case when no network is specified at all and level is below datacenter.

**Comment by vpet98** [comment]
Do we want this for the public method as well? E.g. /public?datacenter=GEOFON&level=network.

**Comment by javiquinte** [comment]
Filtering and grouping should not be mixed, because no one knows how the requirements will evolve in the future.
What @jschaeff mentions is related to the aggregation of data. The filter will be driven by the "network" parameter.
