### ISSUE TITLE
Replace datacenter and network management API with an information method

### ISSUE THREAD

**Issue by jschaeff** [EIDA/eida-statistics#32]
/nodes/id would show the information about a node, which is basically it's default restriction policy

More info could be added in the future, for instance, latest payload submitted ?

**Comment by vpet98** [comment]
There is a /_nodes method already that returns a list of available nodes. Maybe it would be a bit confusing to have similar names. For now, I am thinking of leaving the name /nodes_restriction_policy for this method and I can change it in the future if we decide to add more information about a node to the results of this method.

**Comment by jschaeff** [comment]
OK. 

We should also think about the consistency of node/datacenter terminology ...

As it goes, maybe we should replace all datacenter parameters for node.
