### ISSUE TITLE
Having openapi spec file served on the right protocol (https)

### ISSUE THREAD

**Issue by jschaeff** [EIDA/eida-statistics#36]
In the branch fix_openap3_proto  the deployment uses pyramid_openapi3 delivered by vpet github repository.

Now, we need to force the protocol to https, I don't remember how to do so in the code. @vpet98 can you help ?

It should be configured with an environment variable EIDASTATS_API_PROTO

**Comment by vpet98** [comment]
I made a commit. It should be fine now I think; you can test it and tell me if there is still a problem.

**Comment by jschaeff** [comment]
Thank you. I made a correction on the port. Now it works great : https://ws.resif.fr/eidaws/statistics/1/#/

Merged in branch development and main.
