### ISSUE TITLE
eida_statsman : add interface to manage networks and nodes policy

### ISSUE THREAD

**Issue by jschaeff** [EIDA/eida-statistics#37]
- toggle default policy on a node
  - when an operator tries to change the policy on a node, there is 2 possible behaviours:
    - if default policy is changed to "open", then make sure that all networks is open, show to the operator the list of networks with resulting restriction
    - else, make sure all networks conform to the default policy. Opening networks has to be done manually
- toggle policy on a network
- list policies for networks (optionally filter by node)

**Comment by vpet98** [comment]
Done.
New commands examples:
 - eida_statsman nodes set_group 18 GROUPNAME
 - eida_statsman nodes set_policy 18 1 (if set to 1/True all networks of node turn their inverted_policy to 0 to conform with restriction, whereas if set to 0/False all networks of node with inverted_policy = 1 are printed to inform user that they will become restricted)
 - eida_statsman networks list -n 18 (-n or --node optional)
 - eida_statsman networks set_group 14 Z32015 GROUPNAME
 - eida_statsman networks set_policy 14 Z32015 0

**Comment by jschaeff** [comment]
I added some help messages. Seems good to me!
