### ISSUE TITLE
A simple method to get nodes and networks

### ISSUE THREAD

**Issue by jschaeff** [EIDA/eida-statistics#38]
We miss 2 public endpoints 

- /nodes  to list all nodes in json format with their default policy
- /networks  to list all known networks with their restriction policy

The endpoint _nodes could be deleted.

**Comment by vpet98** [comment]
I changed /_nodes to /nodes and added restriction policy status in the returned objects.

Would a /networks endpoint be practical? To see the restriction policy of a network there is already a /network_restriction_policy endpoint.

**Comment by jschaeff** [comment]
Thanks, I think it would be more convenient to have the /networks method available.
It will be usefull for the dashboard UI
