### ISSUE TITLE
Layout of the documentation

### ISSUE THREAD

**Issue by jschaeff** [EIDA/eida-statistics#39]
- Change the title (Swagger UI -> EIDA statitistics)
- Remove the banner where user can change the opapi.yaml URL

**Comment by vpet98** [comment]
I saw that the pull request we had made to the pyramid_openapi3 repository was merged. Do we want to change back to it instead of using my fork? If yes, then to change what stated above, I will need to add in our repo an index.html file to override the one in their static folder.

**Comment by jschaeff** [comment]
Let's wait for upstream to make a new release. This will make the dependencies more accurate and cleaner. I saw they updated upstream dependencies also.
