### ISSUE TITLE
Extra information at the top of CSV format

### ISSUE THREAD

**Issue by javiquinte** [EIDA/eida-statistics#41]
I like *"a lot"* the extra lines with comments you included at the top of the CSV (#40 ).
Could you please consider to include an extra piece of information?
For instance: rejected or malformed parameters?
```
# request_parameters: start=2022-01&end=2022-12&details=month&format=csv
# rejected_parameters: groupby=day
```

**Comment by jschaeff** [comment]
I'm afraid that if parameters are wrong, user wont get any result.

For instance this URL gets a 400 return code. https://ws.resif.fr/eidaws/statistics/1/dataselect/public?start=2022-01&end=2023-01&aggregate_on=network,station,location,channel,month&format=json

```html

<h1>400 Bad Request</h1><p>Invalid parameter 'aggregate_on'</p>
```

**Comment by jschaeff** [comment]
Maybe we should adapt the error message to the requested format:

- csv can return the proposition of @javiquinte 
- json can also return the message in a json structure

**Comment by javiquinte** [comment]
No, I think you are totally right. If parameters are rejected and the query cannot be executed the user should receive a 40X code and no CSV.
Just taking into account in the future in case that you feel that a query can be executed and returned without doubts of any type and an extra parameter was not used, or does not fit well.
I'll just close the issue.
Thanks!
