### ISSUE TITLE
Sentry: set DSN by environment variable 

### ISSUE THREAD

**Issue by jschaeff** [EIDA/eida-statistics#48]
Could you remove the DSN from the code and get it from an environment variable ?

Also, please look at how to setup the environment (dev, staging, production) so that sentry can make the difference.

https://docs.sentry.io/platforms/go/guides/martini/configuration/environments/

**Comment by vpet98** [comment]
So, I will change the name of the environemnt in the code depending on whether I am developing locally or going to commit on development for staging or on main for production?

Or use an environment variable for this too?

**Comment by jschaeff** [comment]
Use an environment variable for this too :) Like "CONTEXT" or "RUNMODE" as you please.

**Comment by vpet98** [comment]
Ok, done. Development branch. Environment variables: DSN and RUNMODE.

**Comment by jschaeff** [comment]
Deployed in staging and in production.

Thanks !
