### ISSUE TITLE
Adding --bzip2 flag for compressing on the fly

### ISSUE THREAD

**Issue by nikosT** [EIDA/eida-statistics#5]
I would suggest the ability to bzip2 the log file on the fly with a python module like:
[https://www.tutorialspoint.com/python-support-for-bzip2-compression-bz2](https://www.tutorialspoint.com/python-support-for-bzip2-compression-bz2)
 
so the node maintainer could run:
` eida_stats_aggregator --bzip2 --output-directory aggregates fdsnws-requests.log.2020-11-02  fdsnws-requests.log.2020-11-03.bz2`

**Comment by jschaeff** [comment]
Compression is the default behaviour.
