### ISSUE TITLE
Pyramid-openapi3 dependency

### ISSUE THREAD

**Issue by vpet98** [EIDA/eida-statistics#51]
New branch with latest version of pyramid-openapi3 dependency at https://github.com/EIDA/eida-statistics/tree/openapi_dependency.

Tested locally and works, hope it works in production as well.

Tell me when to merge in main.

**Comment by vpet98** [comment]
Any updates on this?

**Comment by jschaeff** [comment]
still on my TODO list, such a shame :)

**Comment by jschaeff** [comment]
test if the swagger page appears when accessing through https

**Comment by jschaeff** [comment]
I tested the branch. You can merge it into main !
