### ISSUE TITLE
Network identifier

### ISSUE THREAD

**Issue by jschaeff** [EIDA/eida-statistics#6]
The aggregator identifies networks only with 2 letters. This is wrong.

Commit 86a36cf7 fixes this.

**Comment by jschaeff** [comment]
Can someone test this new aggregator ?


1. install the new version with the pipenv method
(https://github.com/EIDA/eida-statistics/tree/main/aggregator#install-and-execute)
2. parse an existing logfile and look at the result to see if it looks fine
3. send the statistics

@kbouk thank you for volunteering :) Let me know how it goes in this issue.

**Comment by jschaeff** [comment]
The function datetime.date.fromisoformat() has been introduced in Python 3.7

Do you think the program should be python3.6 compatible ?

**Comment by javiquinte** [comment]
If it's only this error, it would be nice to make it 3.6 compatible. Probably a simple replacement with `strptime` could be enough.

**Comment by jschaeff** [comment]
It would be enough. It's just soo less fun :)

**Comment by jschaeff** [comment]
@kbouk you have to upgrade a dependency of this project : fdsnnetextender == 3.2.0
Can you give it another try ?

**Comment by kbouk** [comment]
Hello @jschaeff,

Yes it works fine now with python 3.6. I am attaching some outputs.
[2022-06-12_2022-06-12.json.gz](https://github.com/EIDA/eida-statistics/files/8919864/2022-06-12_2022-06-12.json.gz)
[2022-06-12_2022-06-13.json.gz](https://github.com/EIDA/eida-statistics/files/8919865/2022-06-12_2022-06-13.json.gz)

**Comment by jschaeff** [comment]
I validated also with temporary networks. The fix is ready to hit the production.
