### ISSUE TITLE
All node upgrade eida-statistics-aggregator to 0.6.0 

### ISSUE THREAD

**Issue by jschaeff** [EIDA/eida-statistics#7]
Hello @ALL

I released a new version for the dataselect statistics aggregator.
This release adds identification of temporary networks by their extended identifier. Wich is important in the statistics because otherwise we mix up statistics from different networks sharing the short network code.

Please all node, could you upgrade ? Depending on your installation method, this should not be much more work than:

    pip3 install --upgrade eida-statistics-aggregator

Please note, minimal python version is 3.6 but it can run in it's isolated environment without problem. It has been tested up to python 3.10

Please report in this issue when you're done:

- [x] ODC 
- [x] GFZ  
- [x] KOERI  
- [x] UIB-NORSAR 
- [x] LMU 
- [x] NIEP  
- [x] ICGC  
- [x] ETH 
- [x] BGR  
- [x] NOA 
- [x] AFAD 
- [x] INGV

**Comment by andres-h** [comment]
GFZ done

**Comment by icarluccio** [comment]
INGV done

**Comment by jschaeff** [comment]
You're awesome !!!

**Comment by cristianneagoe** [comment]
NIEP done

**Comment by jschaeff** [comment]
Hello, @ALL, a kind reminder for the nodes that didn't already upgrade.

Thank you

**Comment by mehmet-ozer-ko** [comment]
KOERI done

**Comment by jschaeff** [comment]
Hello, @jbienkowski , @jan-michalek , @sheimers , a kind reminder for upgrading the aggregator on your side.

Thank you

**Comment by jbienkowski** [comment]
Done at ODC! Thanks for the reminder!

**Comment by sheimers** [comment]
Done at ETH, the first run of the new version will be today at 14:30 utc

**Comment by jan-michalek** [comment]
UIB-NORSAR done now. Sorry for the delay.

**Comment by jschaeff** [comment]
Thank you. Seems OK for UIB. I miss LMU :cry:

**Comment by jschaeff** [comment]
We are done. Thank you all !
