### ISSUE TITLE
Upgrade fdsnnetextender

### ISSUE THREAD

**Issue by jschaeff** [EIDA/eida-statistics#9]
In order to fix #8 , I released a new version of the fdsnnetextender package on wich the aggregator relies.

@all could you make an update of fdsnnetextender on all nodes ?

```
pip install --upgrade fdsnnetextender
```

The targetted version is 3.3.0

- [x] ODC 
- [X] GFZ  
- [x] KOERI  
- [x] UIB-NORSAR 
- [x] LMU 
- [x] NIEP  
- [x] ICGC  
- [x] ETH 
- [x] BGR  
- [x] NOA 
- [x] INGV

**Comment by jschaeff** [comment]
Hello @sheimers @mehmet-ozer-ko @cristianneagoe if you have some time to update fdnsnnetextender so we can close the issue.

Thanks !

**Comment by mehmet-ozer-ko** [comment]
KOERI is done

**Comment by cristianneagoe** [comment]
Done at NIEP

**Comment by jschaeff** [comment]
Awesome, thank you @all !
